title: Grazielly de Melo Oliveira
description: > # this means to ignore newlines until "baseurl:"
  Grazielly de Melo Oliveira is an SF-based entrepreneur, startup consultant, writer, & speaker. Currently writing a book on The New Distributed Workforce.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://grazimelo.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: "https://twitter.com/graziellymelo" #if your site has a twitter account, enter it here

# Author Settings
author: Grazielly Oliveira # add your name
author-img: gra headshot.jpg # add your photo
about-author: Sou Grazielly, tenho 23 anos, graduanda em química e apaixonada por tecnologia, hoje dedico meu tempo a Ciência de Dados. Com intuito de mostrar o meu trabalho com dados resolvi criar um lugar para organizar meus projetos. # add description
social-facebook: grazielly.melo.3 # add your Facebook handle
social-github: grazimelo # ig handle
social-linkedin: grazielly-de-melo-04a9a8178 # add your Linkedin handle
social-email: grazy-melo@live.com # add your Email address

# Disqus
discus-identifier: Grazielly Oliveira # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
